export const CHECKING = "CHECKING";
export const UPDATE_PERMISSIONS = "UPDATE_PERMISSIONS";
export const REQUESTING_PERMISSION = "REQUESTING_PERMISSION";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAIL = "REQUEST_FAIL";
export const NOT_CHECKING = "NOT_CHECKING";
